# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-15 00:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.IntegerField()),
            ],
            managers=[
                ('useru', django.db.models.manager.Manager()),
            ],
        ),
    ]
